### ISSUE TITLE
Integration of the payment form in an iFrame

### ISSUE THREAD

**Issue by motame** [pfpayments/php-sdk#2]
I am sorry to put this request here !
I did not find any way to contact you. I end-up by opening this issue.
Thank you very much for the API.

I tried the example provided where it redirects to [Postfinance server](https://checkout.postfinance.ch) and it works like a sharme:
```php
// Create Payment Page URL:
$redirectionUrl = $client->getTransactionPaymentPageService()->paymentPageUrl($spaceId, $transaction->getId());
header('Location: ' . $redirectionUrl);

```
Thank you very much.
 I tried afterwards to integrate the same content in an iFrame but I failed !
 I want to see the same form content in an iFrame instead of the redirection : 

![firefox_SPoguUo0Jb](https://user-images.githubusercontent.com/44972498/185145425-18034852-b437-4851-9d5e-412003deb125.png)

I followed to do that the Postfinance doc:
https://checkout.postfinance.ch/fr-ch/doc/payment/iframe

Hereafter the example code : 
```php
<?php
require_once (__DIR__ . '/autoload.php');

// Configuration
$spaceId = 123;
$userId = 456;
$secret = 'Z5rjzp8zDUuYRjkxWcvsdwsWA18b7VYf/x+0=';

// Setup API client
$client = new \PostFinanceCheckout\Sdk\ApiClient($userId, $secret);

// Create transaction
$lineItem = new \PostFinanceCheckout\Sdk\Model\LineItemCreate();
$lineItem->setName('Red T-Shirt');
$lineItem->setUniqueId('5412');
$lineItem->setSku('red-t-shirt-123');
$lineItem->setQuantity(1);
$lineItem->setAmountIncludingTax(30);
$lineItem->setType(\PostFinanceCheckout\Sdk\Model\LineItemType::PRODUCT);

$transactionPayload = new \PostFinanceCheckout\Sdk\Model\TransactionCreate();
$transactionPayload->setCurrency('CHF');
$transactionPayload->setLanguage('FR');
$transactionPayload->setLineItems(array($lineItem));
$transactionPayload->setAutoConfirmationEnabled(true);

$transaction = $client->getTransactionService()->create($spaceId, $transactionPayload);

$javascriptUrl = $client->getTransactionIframeService()->javascriptUrl($spaceId, $transaction->getId());

?>

<ul id="payment-errors"></ul>
<div id="payment-form"></div>
<button id="pay-button">Pay</button>

<script src="jquery.js" type="text/javascript"></script>
<script src="<?=$javascriptUrl?>" type="text/javascript"></script>
<script type="text/javascript">
// Set here the id of the payment method configuration the customer chose.
var paymentMethodConfigurationId = 1;

// Set here the id of the HTML element the payment iframe should be appended to.
var containerId = 'payment-form';

var handler = window.IframeCheckoutHandler(paymentMethodConfigurationId);

handler.setValidationCallback(
	function(validationResult){
		// Reset payment errors
		$('#payment-errors').html('');

		if (validationResult.success) {
			// Create the order within the shop and eventually update the transaction.
			$.ajax('http://your-shop-backend.com/create-order', {
				success: function(){
					handler.submit();
				}
			});
		} else {
			// Display errors to customer
			$.each(validationResult.errors, function(index, errorMessage){
				$('#payment-errors').append('<li>' + errorMessage + '</li>');
			});
		}
	});

//Set the optional initialize callback
handler.setInitializeCallback(function(){
		//Execute initialize code
	});

//Set the optional height change callback
handler.setHeightChangeCallback(function(height){
		//Execute code
	});

handler.create(containerId)


$('#pay-button').on('click', function(){
	handler.validate();
});
</script>

```

And here is the error .

![firefox_0fkEgS6XbY](https://user-images.githubusercontent.com/44972498/185150902-aec32018-7a14-464d-bcd7-d53479000de0.png)

The source dode : 

![firefox_V1P1OtNwMa](https://user-images.githubusercontent.com/44972498/185150983-27144ade-5b29-4b0a-9342-9fc08de93167.png)

Is it the right way to go or there is may be a simpler way to achieve that ?
Thank you again,

**Comment by 3rdlevelepi** [comment]
Hi,

Thank you for contacting us.
For any further questions you can contact our support via ***@***.***

From what I see, the "paymentMethodConfiguration": { should be empty.
Could you try it without giving an ID?

Yours sincerely,

Anina Vera Cavaliere

PostFinance Ltd
Merchant Support E-Payment

Phone: +41 848 382 423
Mon-Fri  8.00 - 17.00 h

E-mail: ***@***.***
www.postfinance.ch



---- Original message ----
From: motame ***@***.***>
Received: Aug 17, 2022, 4:02 PM
To: pfpayments/php-sdk ***@***.***>
Subject: [pfpayments/php-sdk] Integration of the payment form in an iFrame (Issue #2)

> I am sorry to put this request here !
> I did not find any way to contact you. I end-up by opening this issue.
> Thank you very much for the API.
>
> I tried the example provided where it redirects to Postfinance server and it works like a sharme:
>
> // Create Payment Page URL:
> $redirectionUrl = $client->getTransactionPaymentPageService()->paymentPageUrl($spaceId, $transaction->getId());
> header('Location: ' . $redirectionUrl);
>
>
> Thank you very much.
>
> I tried afterwards to integrate the same content in an iFrame but I failed !
>
> I want to see the same form content in an iFrame instead of the redirection :
>
>
>
>
>
> I followed to do that the Postfinance doc:
>
> https://checkout.postfinance.ch/fr-ch/doc/payment/iframe
>
>
> Hereafter the example code :
>
>
> <?php
> require_once (__DIR__ . '/autoload.php');
>
> // Configuration
> $spaceId = 123;
> $userId = 456;
> $secret = 'Z5rjzp8zDUuYRjkxWcvsdwsWA18b7VYf/x+0=';
>
> // Setup API client
> $client = new \PostFinanceCheckout\Sdk\ApiClient($userId, $secret);
>
> // Create transaction
> $lineItem = new \PostFinanceCheckout\Sdk\Model\LineItemCreate();
> $lineItem->setName('Red T-Shirt');
> $lineItem->setUniqueId('5412');
> $lineItem->setSku('red-t-shirt-123');
> $lineItem->setQuantity(1);
> $lineItem->setAmountIncludingTax(30);
> $lineItem->setType(\PostFinanceCheckout\Sdk\Model\LineItemType::PRODUCT);
>
> $transactionPayload = new \PostFinanceCheckout\Sdk\Model\TransactionCreate();
> $transactionPayload->setCurrency('CHF');
> $transactionPayload->setLanguage('FR');
> $transactionPayload->setLineItems(array($lineItem));
> $transactionPayload->setAutoConfirmationEnabled(true);
>
> $transaction = $client->getTransactionService()->create($spaceId, $transactionPayload);
>
> $javascriptUrl = $client->getTransactionIframeService()->javascriptUrl($spaceId, $transaction->getId());
>
> ?>
>
> <ul id="payment-errors"></ul>
> <div id="payment-form"></div>
> <button id="pay-button">Pay</button>
>
> <script src="jquery.js" type="text/javascript"></script>
> <script src="<?=$javascriptUrl?>" type="text/javascript"></script>
> <script type="text/javascript">
> // Set here the id of the payment method configuration the customer chose.
> var paymentMethodConfigurationId = 1;
>
> // Set here the id of the HTML element the payment iframe should be appended to.
> var containerId = 'payment-form';
>
> var handler = window.IframeCheckoutHandler(paymentMethodConfigurationId);
>
> handler.setValidationCallback(
> function(validationResult){
> // Reset payment errors
> $('#payment-errors').html('');
>
> if (validationResult.success) {
> // Create the order within the shop and eventually update the transaction.
> $.ajax('http://your-shop-backend.com/create-order', {
> success: function(){
> handler.submit();
> }
> });
> } else {
> // Display errors to customer
> $.each(validationResult.errors, function(index, errorMessage){
> $('#payment-errors').append('<li>' + errorMessage + '</li>');
> });
> }
> });
>
> //Set the optional initialize callback
> handler.setInitializeCallback(function(){
> //Execute initialize code
> });
>
> //Set the optional height change callback
> handler.setHeightChangeCallback(function(height){
> //Execute code
> });
>
> handler.create(containerId)
>
>
> $('#pay-button').on('click', function(){
> handler.validate();
> });
> </script>
>
>
> And here is the error .
>
>
>
>
>
> The source dode :
>
>
>
>
>
> Is it the right way to go or there is may be a simpler way to achieve that ?
>
> Thank you again,
>
>
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Security note:
This e-mail was signed by PostFinance. Further information can be found at: 
https://www.postfinance.ch/e-signature.
Never disclose your security features to third parties.
