### ISSUE TITLE
Reading a Transaction with an unrelated SpaceId leads to an empty Transaction Object instead of an Exception

### ISSUE THREAD

**Issue by ravage84** [pfpayments/php-sdk#3]
PHP-SDK: 3.1.2
PHP 7.2
Composer installed

When one attempts to read a transaction through the SDK with an unrelated spaceId, it will return an  empty transaction object. This is quite unexpected as reading/getting a single item through SDKs normally leads to an exception and not just an empty object.

But it seems this is due to the behavior of the API itself, not just the SDK, as it returns a 200 OK in such a case:

![grafik](https://user-images.githubusercontent.com/625761/187426070-9076fbc1-1c79-415b-a290-ff4d1d935060.png)

https://checkout.postfinance.ch/api/client/transaction-service--read

Relevant code:

https://github.com/pfpayments/php-sdk/blob/3990276041e1d369e1622be78b5831ae4587beb5/lib/Service/TransactionService.php#L152

Would it be possible to change this behavior in future releases of the SDK?

**Comment by theodorspringwallee** [comment]
Dear [ravage84](https://github.com/ravage84)

Thank you for your proposal. We will check this.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [ravage84](https://github.com/ravage84)

According to our developers, this is the standard behavior, and we can't change this on our side.

Here you find the full explanation:

> This is expected behavour. The reason is the following: the user account used to run the query has the access rights to read transactions. 
However, based on the role assignment, the user has no access to the other space. 
In our query code the space restriction is applied on a row level to filter the rows. 
Hence, the result here is an “empty result set” and not an exception. 
This is not possible to change and has always been working like this since the beginning of wallee. 
It also works the same way if the space ID is correct, but the transaction ID does not belong to that space.

I hope this will answer your questions.

Best regards

**Comment by ravage84** [comment]
@theodorspringwallee thanks for answer.

Yes, it answers my question.

Nontheless, please take back the following feedback:

From a develoepr perspective, this is unexpected and certainly unwanted behavior. For us and our customer, it is irrelevant how long something has been the way it is now, even though we can relate to situations like this.

Either the API or the SDK should consider to change this in a backwards compatibility breaking major release.

Thanks.

**Comment by theodorspringwallee** [comment]
Dear [ravage84](https://github.com/ravage84)

Thanks for your feedback. I just forwarded your feedback. 

Best regards

**Comment by theodorspringwallee** [comment]
Dear [ravage84](https://github.com/ravage84)

Our developer has here the final statement to your feedback:
>To clarify the issue here a bit more. Unfortunately this is one of those things which is embedded quite deeply into wallee code and as I mention would be impossible to change without having to refactor a lot of things.

>On the other hand, it can also be looked another way. When you do a normal SQL query but give wrong parameters, the result is typically and empty result set. This is what happens here, because the code used to query ONE transaction is the same code you would use to query multiple ones (e.g. by filtering on date or something like that). So when you look at it like that it makes sense why here it behaves in this way.

>Also the last reason we can’t change it now is simply because already this API exists for a long time and there could be merchants who already rely on this behaviour. Generally we can’t change our REST/SDK API in ways which make it backwards incompatible.

>So from multiple standpoints making a change like this is pretty much 100% a no-go.

>Also a final clarification: as merchant suspected, this “issue” is entirely on portal side and has nothing to do with the SDK implementation itself.

I hope this helps as final statement/clarification.

Best regards
