### ISSUE TITLE
How to limit payment connectors to a list of IDs

### ISSUE THREAD

**Issue by JainJayan** [pfpayments/php-sdk#6]
I have a connector with an ID (e.g. 123). How can I start a lightbox transaction that only shows this payment method?

This code shows an error, that the ID is not known:

```php
$transactionCreate = new TransactionCreate([]);
$transactionCreate->setAllowedPaymentMethodConfigurations([123]);
```

Is it not the ID shown next to the payment connector?

![image](https://github.com/pfpayments/php-sdk/assets/99398736/3c988658-7cc9-477d-9b4a-6c522a4a8f50)

**Comment by theodorspringwallee** [comment]
Dear [JainJayan](https://github.com/JainJayan)

Here it's about the allowed payment method configuration (not the connectors)

So please go under Settings > Payment > Payment Methods and choose the concerned payment method, where you see the ID (example image):
![grafik](https://github.com/pfpayments/php-sdk/assets/85299706/6cd3ccf9-be18-42c6-8751-94737f16e15d)

Best regards

**Comment by JainJayan** [comment]
Thanks! That was very helpful!
